#!/bin/sh
set -x

cp /secrets/munge/munge.key /etc/munge/munge.key
mkdir -p /etc/munge /var/lib/munge /var/log/munge /var/run/munge
chown -R munge: /etc/munge /var/lib/munge /var/log/munge /var/run/munge
set -e
s6-setuidgid munge /usr/sbin/munged -F
