#!/bin/sh
set -x

cp -p /secrets/munge/munge.key /etc/munge/munge.key
mkdir -p /etc/munge /var/lib/munge /var/log/munge /var/run/munge
chown -R munge: /etc/munge /var/lib/munge /var/log/munge /var/run/munge
chmod 600 /etc/munge/munge.key
set -e
s6-setuidgid munge /usr/sbin/munged -F
