#!/usr/bin/env sh

runtime_path="/run/enroot/user-$SLURM_JOB_UID"
mkdir -p "$runtime_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$runtime_path"
chmod 0775 "$(dirname "$runtime_path")"
chmod 0700 "$runtime_path"

cache_path="/mnt/beegfs/enroot/cache/group-$(id -g "$SLURM_JOB_UID")"
mkdir -p "$cache_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$cache_path"
chmod -R 0770 "$cache_path"

data_path="/mnt/beegfs/enroot/containers/user-$SLURM_JOB_UID/$(cat /etc/hostname)"
mkdir -p "$data_path"
chown -R "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "/mnt/beegfs/enroot/containers/user-$SLURM_JOB_UID"
chmod -R 0700 "/mnt/beegfs/enroot/containers/user-$SLURM_JOB_UID"

