#!/bin/bash
set -ex

cp /secrets/slurm/jwt_hs256.key /etc/slurm/jwt_hs256.key

while ! id slurm; do
  sleep 1
done
chown slurm:slurm /etc/slurm/jwt_hs256.key
chmod 0600 /etc/slurm/jwt_hs256.key
chown root:root /etc/slurm
chmod 0755 /etc/slurm
export SLURM_JWT=daemon
s6-applyuidgid -u "$(id api -u)" -g "$(id api -g)" /usr/sbin/slurmrestd 127.0.0.1:6820
