#!/command/with-contenv sh
set -x
mkdir -p /var/spool/slurm

while ! id slurm; do
  sleep 1
done
chown root:root /etc/slurm
chmod 0755 /etc/slurm
set -e

if [ "${GPU_ACCT}" = "true" ]; then
  /usr/sbin/slurm-prometheus-exporter -gpus-acct
else
  /usr/sbin/slurm-prometheus-exporter
fi
