#!/bin/bash
set -x
mkdir -p /var/spool/slurm
cp /secrets/slurm/jwt_hs256.key /var/spool/slurm/jwt_hs256.key

while ! id slurm; do
  sleep 1
done
chown slurm:slurm /var/spool/slurm/jwt_hs256.key
chmod 0600 /var/spool/slurm/jwt_hs256.key
chown root:root /etc/slurm
chmod 0755 /etc/slurm
chown -R slurm: /var/spool/slurmctl /var/run/slurmctl
set -e
/usr/sbin/slurmctld -D
