#!/bin/bash
set -ex
cp /secrets/jwt_hs256.key /var/spool/slurmctl/jwt_hs256.key || echo "Copy file has failed"

while ! id slurm
do
  sleep 1
done
chown -R slurm: /var/spool/slurmctl /var/run/slurmctl
/usr/sbin/slurmctld -D
