#!/bin/bash
set -ex
cp /secrets/jwt_hs256.key /var/spool/slurmctl/jwt_hs256.key || echo "Copy file has failed"

while ! id slurm
do
  sleep 1
done
chown -R slurm: /var/spool/slurm /var/run/slurm
s6-applyuidgid -u "$(id slurm -u)" -g "$(id slurm -g)" /usr/sbin/slurmd -D
